# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    # add dot files to homedir
    config.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig", run: "always"
    config.vm.provision "file", source: "~/.gitignore", destination: "~/.gitignore", run: "always"
    config.vm.provision "file", source: "~/.profile", destination: "~/.bashrc", run: "always"
    config.vm.provision "file", source: "~/.aliases", destination: "~/.bash_aliases", run: "always"
    config.vm.provision "file", source: "~/.vimrc", destination: "~/.vimrc", run: "always"
    config.vm.provision "shell", inline: "touch /etc/vagrantbox", run: "always"
    
    # forward gpg keys
    config.ssh.extra_args = [ "-o", "RemoteForward /home/vagrant/.gnupg/S.gpg-agent /Users/cole/.gnupg/S.gpg-agent.extra" ]
end
