#!/bin/bash
# Stops accidental pushes to master and develop.

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$BRANCH" == "master" ]]; then
    echo "You are on branch $BRANCH. Are you sure you want to push to this branch?"
    exit 1
fi

exit 0
